# Generated by Django 4.2.20 on 2025-04-10 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apesf', '0002_remove_pagecontent_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse email')),
                ('message', models.TextField(verbose_name='Message')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='pagecontent',
            options={'verbose_name': 'Contenu de page', 'verbose_name_plural': 'Contenus de page'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['order'], 'verbose_name': 'Section', 'verbose_name_plural': 'Sections'},
        ),
        migrations.AlterModelOptions(
            name='uploadedimage',
            options={'verbose_name': 'Image uploadée', 'verbose_name_plural': 'Images uploadées'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Profil utilisateur', 'verbose_name_plural': 'Profils utilisateurs'},
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug (URL)'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour'),
        ),
        migrations.AlterField(
            model_name='section',
            name='content',
            field=models.TextField(verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='section',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='section',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Lien (optionnel)'),
        ),
        migrations.AlterField(
            model_name='section',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordre d’affichage'),
        ),
        migrations.AlterField(
            model_name='section',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='apesf.pagecontent', verbose_name='Page associée'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='section',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='image',
            field=models.ImageField(upload_to='uploads/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='apesf.section', verbose_name='Section associée'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date d’upload'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('superuser', 'Super utilisateur (Accès total : peut supprimer des utilisateurs et du contenu. Rôle le plus puissant.)'), ('admin', 'Administrateur (Peut créer, modifier et supprimer du contenu. Aucun accès aux actions irréversibles comme la suppression des utilisateurs.)'), ('viewer', 'Lecteur (Accès en lecture et modification mineure du texte. Aucun pouvoir sur la structure ou les utilisateurs.)')], max_length=50, verbose_name='Rôle'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
