# Generated by Django 4.2.20 on 2025-04-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apesf', '0003_contactmessage_alter_pagecontent_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='partner_logos/')),
            ],
        ),
    ]
