# Generated by Django 4.2.20 on 2025-04-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apesf', '0004_partner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Partenaire', 'verbose_name_plural': 'Partenaires'},
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(upload_to='partner_logos/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom du partenaire'),
        ),
    ]
