# Generated by Django 4.2.20 on 2025-04-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apesf', '0005_alter_partner_options_alter_partner_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Description courte'),
        ),
    ]
