# Generated by Django 4.2.20 on 2025-04-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apesf', '0007_remove_partner_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
