# Generated by Django 4.2.20 on 2025-04-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apesf', '0010_section_unit_alter_section_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('date', models.DateField(verbose_name='Date')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='Image (optionnelle)')),
                ('document', models.FileField(blank=True, null=True, upload_to='news_documents/', verbose_name='Pièce jointe (PDF, DOCX, TXT, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Actualité',
                'verbose_name_plural': 'Actualités',
                'ordering': ['-date'],
            },
        ),
    ]
