# Generated by Django 4.2.20 on 2025-04-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apesf', '0011_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('posted_date', models.DateField(auto_now_add=True)),
                ('email_contact', models.EmailField(max_length=254)),
                ('document', models.FileField(blank=True, null=True, upload_to='job_documents/')),
            ],
            options={
                'ordering': ['-posted_date'],
            },
        ),
    ]
