# Generated by Django 4.2.20 on 2025-05-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apesf', '0012_joboffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='unit',
            field=models.CharField(blank=True, choices=[('marmousets', 'Marmousets'), ('angelus', 'Angélus'), ('placement_modulable', 'Placement modulable'), ('accueil_parental', 'Accueil parental'), ('', 'Aucune unité')], default='', max_length=50, verbose_name='Unité associée'),
        ),
    ]
