# Generated by Django 4.2.20 on 2025-05-05 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apesf', '0012_joboffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='apesf.uploadedimage', verbose_name='Image associée'),
        ),
    ]
