# Generated by Django 4.2.20 on 2025-05-06 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apesf', '0013_alter_section_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Objet'),
        ),
        migrations.CreateModel(
            name='ContactMessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='contact_attachments/', verbose_name='Pièce jointe')),
                ('contact_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='apesf.contactmessage', verbose_name='Message de contact')),
            ],
            options={
                'verbose_name': 'Pièce jointe de message de contact',
                'verbose_name_plural': 'Pièces jointes de messages de contact',
            },
        ),
    ]
