# Generated by Django 4.2.20 on 2025-05-09 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apesf', '0014_contactmessage_subject_contactmessageattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='apesf.news', verbose_name='Actualité associée'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='Image principale (optionnelle)'),
        ),
    ]
