# Generated by Django 4.2.20 on 2025-05-15 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apesf', '0015_uploadedimage_news_alter_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='transferred_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_messages', to=settings.AUTH_USER_MODEL, verbose_name='Transféré à'),
        ),
    ]
