# Generated by Django 4.2.20 on 2025-05-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apesf', '0016_contactmessage_transferred_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='transferred_to',
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(blank=True, choices=[('question', 'Question générale'), ('partenariat', 'Demande de partenariat'), ('adhesion', 'Adhésion à l’association'), ('don', 'Faire un don'), ('stage', 'Demande de stage'), ('candidature', 'Candidature spontanée'), ('evenement', 'Participer à un événement'), ('autre', 'Autre')], default='', max_length=200, verbose_name='Objet'),
        ),
    ]
