# Generated by Django 4.2.20 on 2025-05-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apesf', '0017_remove_contactmessage_transferred_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='organigram_type',
            field=models.CharField(blank=True, choices=[('', 'Aucun'), ('direction', 'Direction'), ('structure', 'Structure')], default='', max_length=50, verbose_name="Type d'organigramme"),
        ),
    ]
