# Generated by Django 4.2.20 on 2025-05-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apesf', '0019_alter_section_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArborescenceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default="Arborescence du conseil d'administration", max_length=200)),
                ('file', models.FileField(help_text="Fichier contenant l'arborescence du conseil d'administration", upload_to='arborescence/')),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, help_text='Description du fichier')),
            ],
            options={
                'verbose_name': "Fichier d'arborescence",
                'verbose_name_plural': "Fichiers d'arborescence",
            },
        ),
    ]
