# Generated by Django 4.2.20 on 2025-06-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apesf', '0020_arborescencefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='description',
            field=models.TextField(blank=True, help_text="Description affichée dans le modal de l'organigramme entre l'image et le bouton de téléchargement", null=True, verbose_name="Description pour l'organigramme"),
        ),
        migrations.AlterField(
            model_name='section',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage"),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout"),
        ),
    ]
