# Generated by Django 4.2.20 on 2025-06-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apesf', '0021_section_description_alter_section_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_login_completed',
            field=models.BooleanField(default=False, verbose_name='Première connexion effectuée'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='must_change_password',
            field=models.BooleanField(default=True, help_text="Si coché, l'utilisateur sera obligé de changer son mot de passe à la prochaine connexion", verbose_name='Doit changer le mot de passe'),
        ),
    ]
