# Generated by Django 4.2.20 on 2025-06-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apesf', '0022_userprofile_first_login_completed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carousel/', verbose_name='Image du carrousel')),
                ('title', models.CharField(help_text="Texte alternatif pour l'accessibilité", max_length=200, verbose_name="Titre de l'image")),
                ('description', models.TextField(blank=True, help_text="Description optionnelle de l'image", verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Image du carrousel',
                'verbose_name_plural': 'Images du carrousel',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='section',
            name='description',
            field=models.TextField(blank=True, help_text="Description affichée dans le modal de l'organigramme entre l'image et le bouton", null=True, verbose_name="Description pour l'organigramme"),
        ),
    ]
